server:
  port: 8193
  servlet:
    context-path: /android-emulator

integrations:
  biometric-service:
    url: http://localhost:8888/api/v1/auth/biometric/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000
  session-service:
    url: http://localhost:8337/api/v1/sessions
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000