server:
  port: 8337

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/session_tracing_service
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6387

  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

sessions:
  page:
    quantity: 20
  life:
    days: 183
    task:
      cron:
        value: 0 * * * * ?
