server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/biometric_service_postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true

integrations:
  session-tracing-service:
    url: http://localhost:8337/api/v1/sessions
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000